import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:wine_advisor/screens/login_screen.dart';
import 'package:wine_advisor/screens/home_screen.dart';
export 'package:wine_advisor/screens/home_screen.dart';
import 'package:google_fonts/google_fonts.dart';

// === GESTIONE LINGUA GLOBALE (DIZIONARIO COMPLETO & PERSISTENTE) ===
final ValueNotifier<String> appLang = ValueNotifier('it');

String t(String key) {
  const dict = {
    'it': {
      'hello': 'Ciao',
      'hero_title': 'Cosa guida la\ntua serata?',
      'hero_sub': 'Scegli il tuo percorso per trovare il vino perfetto.',
      'food_title': 'Ho già il menù',
      'food_sub': 'Trova l\'abbinamento perfetto per il tuo piatto.',
      'mood_title': 'Cerco l\'atmosfera',
      'mood_sub': 'Un vino per ogni emozione e situazione.',
      'search_title': 'Cosa mangi stasera?',
      'search_hint': 'Es. Carbonara, Sushi, Filetto...',
      'search_empty': 'Inizia a digitare o tocca un suggerimento...',
      'pairing': 'Abbinamento:',
      'mood_appbar': 'Come ti senti?',
      'mood_hint': 'Es. Rilassato, Romantico, Festoso...',
      'mood_empty': 'Descrivi il tuo mood o tocca un suggerimento...',
      'profile_title': 'La Mia Cantina',
      'profile_empty_title': 'Nessun abbinamento salvato.',
      'profile_empty_sub': 'Esplora l\'app e salva i tuoi preferiti!',
      'profile_deleted': 'Abbinamento rimosso dalla cantina 🗑️',
      'result_title': 'Il tuo Abbinamento',
      'result_recommended': 'Ti consigliamo:',
      'result_examples': 'Esempi:',
      'result_why': 'Perché questa scelta?',
      'result_temp': 'Temperatura ideale:',
      'result_save': 'Salva',
      'result_saved': 'Abbinamento salvato nei preferiti! 🍷',
      'result_saved_btn': 'Salvato nei preferiti',
      'result_removed': 'Abbinamento rimosso dai preferiti',
      'must_login_to_save': 'Accedi per salvare i tuoi preferiti nella cantina.',
      'result_dup': 'Hai già salvato questo abbinamento!',
      'share_text_1': '🍷 Stasera si beve bene!\n\nLa mia app consiglia: *',
      'share_text_2': '*\nEsempi: ',
      'share_text_3': '\n\nTemperatura ideale: ',
      'share_copied': 'Testo copiato! Incollalo su WhatsApp. 📋',
      'login_title': 'Wine Advisor',
      'login_btn': 'Accedi',
      'register_btn': 'Registrati',
      'login_prompt': 'Non hai un account? Registrati',
      'register_prompt': 'Hai già un account? Accedi',
      'continue_as_guest': 'Continua come ospite',
      'guest': 'Ospite',
      'guest_title': 'Gentile Ospite',
      'guest_profile_msg': 'Accedi o registrati per salvare i tuoi abbinamenti preferiti e consultarli in qualsiasi momento.',
      'guest_login_btn': 'Accedi / Registrati',
      'email': 'Email',
      'password': 'Password',
      'reg_success': 'Registrazione completata! Ora puoi accedere.',
      'quick_suggestions': 'Suggerimenti rapidi:',
      'chip_meat': '🥩 Bistecca',
      'chip_fish': '🐟 Pesce',
      'chip_pasta': '🍝 Carbonara',
      'chip_pizza': '🍕 Pizza',
      'chip_sushi': '🍣 Sushi',
      'chip_dessert': '🍰 Dolce',
      'chip_romantic': '🕯️ Romantico',
      'chip_party': '🎉 Festoso',
      'chip_relax': '🛋️ Rilassato',
      'chip_friends': '🥂 Aperitivo',
      'all': 'Tutti',
      'food_empty_title': 'Nessun piatto trovato',
      'food_show_all': 'Mostra tutti i piatti',
      'mood_empty_title': 'Nessuna atmosfera trovata',
      'mood_show_all': 'Mostra tutte le atmosfere',
      'refresh': 'Aggiorna',
      'or': 'oppure',
      'share_tooltip': 'Condividi',
      'wine_lover': 'Appassionato di Vino',
      'change_lang': 'Cambia Lingua',
      'profile': 'Profilo',
      'logout': 'Esci',
      'error_prefix': 'Errore',
      'network_error': 'Impossibile connettersi al database. Verifica che il progetto Supabase sia attivo.',
      'my_tasting': 'La tua Degustazione',
      'tasting_notes': 'Note di Degustazione',
      'rate_wine': 'Valuta questo vino',
      'rating_label': 'Valutazione',
      'not_rated': 'Non ancora valutato',
      'stars_count': 'stelle su 5',
      'notes_hint': 'Scrivi qui le tue impressioni, annata, piatto provato, con chi eri...',
      'add_notes': 'Aggiungi appunto',
      'edit_notes': 'Modifica appunto',
      'save_notes': 'Salva appunto',
      'notes_saved': 'Appunto salvato con successo! 📝',
      'delete_notes': 'Elimina nota',
      'cancel': 'Annulla',
      'no_notes_cantina': 'Nessuna nota aggiunta. Tocca per scrivere un appunto o valutare.',

      // Quiz del Sommelier
      'quiz_card_title': 'Quiz del Sommelier',
      'quiz_card_sub': '3 domande per trovare il tuo calice ideale.',
      'quiz_card_badge': '✨ Consigliato',
      'quiz_step_of': 'Passo {current} di {total}',
      'quiz_step_1_title': 'Qual è il mood della serata?',
      'quiz_step_1_sub': 'Scegli l\'atmosfera o l\'occasione',
      'quiz_step_2_title': 'Cosa desidera il tuo palato?',
      'quiz_step_2_sub': 'Il profilo di gusto che preferisci stasera',
      'quiz_step_3_title': 'Con chi dividerai questo calice?',
      'quiz_step_3_sub': 'La compagnia perfetta fa la differenza',
      'quiz_q1_opt1': 'Aperitivo informale o relax',
      'quiz_q1_opt2': 'Cena romantica o per fare colpo',
      'quiz_q1_opt3': 'Grigliata o cena ricca di sapori',
      'quiz_q1_opt4': 'Pizza, pasta o divano & serie TV',
      'quiz_q2_opt1': 'Freschezza, profumi floreali e vivacità',
      'quiz_q2_opt2': 'Bollicine fini, brio ed eleganza',
      'quiz_q2_opt3': 'Corpo caldo, tannini decisi e struttura',
      'quiz_q2_opt4': 'Fruttato, leggero, morbido e beverino',
      'quiz_q3_opt1': 'In coppia (un momento intimo)',
      'quiz_q3_opt2': 'Gruppo di amici affamati e allegri',
      'quiz_q3_opt3': 'Famiglia o ospiti a tavola',
      'quiz_q3_opt4': 'Da solo/a per un meritato relax',
      'quiz_analyzing': 'Il Sommelier sta selezionando il calice perfetto...',
      'quiz_match_title': 'Ecco il tuo abbinamento ideale!',
      'quiz_affinity': 'Affinità del Sommelier',
      'quiz_why_match': 'Perché è perfetto per te:',
      'quiz_see_details': 'Scopri bottiglie e dettagli',
      'quiz_retake': 'Rifai il Quiz',

      // Modalità Inversa (Reverse Pairing)
      'reverse_card_title': 'Ho già la bottiglia',
      'reverse_card_sub': 'Cosa cucino? Trova i piatti ideali per il tuo vino.',
      'reverse_title': 'Abbinamento Inverso',
      'reverse_subtitle': 'Scegli o cerca il vino che hai a casa per scoprire cosa abbinare:',
      'reverse_search_hint': 'Cerca per nome (es. Barolo, Chianti, Prosecco...)',
      'reverse_dishes_title': 'Piatti e ricette consigliate',
      'reverse_chef_tip': 'Consiglio dello Chef:',
      'reverse_why': 'Perché funziona:',
      'reverse_filter_all': 'Tutti',
      'reverse_filter_primi': '🍝 Primi',
      'reverse_filter_meat': '🥩 Carne',
      'reverse_filter_fish': '🐟 Pesce',
      'reverse_filter_pizza': '🍕 Pizza & Street',
      'reverse_filter_cheese': '🧀 Formaggi',
      'reverse_no_dishes': 'Nessun piatto trovato per questo filtro.',

      // Calcolatore Bottiglie
      'calc_card_title': 'Calcolatore Bottiglie',
      'calc_card_sub': 'Quante bottiglie servono per la tua cena o festa?',
      'calc_card_badge': 'Party & Cene',
      'calc_title': 'Calcolatore Bottiglie',
      'calc_subtitle': 'Pianifica le bevute per cene ed eventi senza rimanere a secco né sprecare vino.',
      'calc_guests_title': 'Numero di Ospiti',
      'calc_guests_unit': 'ospiti',
      'calc_occasion_title': 'Tipo di Occasione',
      'calc_occ_aperitivo': '🥂 Aperitivo',
      'calc_occ_casual': '🍕 Pizza & Casual',
      'calc_occ_dinner': '🍷 Cena Completa',
      'calc_occ_party': '🎉 Festa tra amici',
      'calc_style_title': 'Stile di Bevuta',
      'calc_style_light': 'Leggero (moderato)',
      'calc_style_med': 'Standard (buoni intenditori)',
      'calc_style_heavy': 'Festoso (serata lunga)',
      'calc_result_title': 'Bottiglie Consigliate',
      'calc_total_bottles': 'Bottiglie Totali',
      'calc_reserve_badge': 'incl. 1 riserva',
      'calc_glasses_est': 'Stima calici totali:',
      'calc_sparkling': 'Bollicine / Spumante',
      'calc_white': 'Vini Bianchi / Rosati',
      'calc_red': 'Vini Rossi',
      'calc_reserve': 'Bottiglia di Riserva / Scorta',
      'calc_reserve_tip': 'Consiglio del Sommelier: Tieni sempre 1 bottiglia di riserva in fresco o in cantina. Se la serata decolla e si prolunga, salverà l\'atmosfera!',
      'calc_share_btn': 'Condividi Lista Spesa Vini',
      'calc_share_copied': 'Lista spesa vini copiata negli appunti! 📋',
      'calc_share_text_1': '🍷 *Lista Vini per l\'Evento*\nOspiti: ',
      'calc_share_text_2': ' persone\nOccasione: ',
      'calc_share_text_3': '\n\n🍾 *Bottiglie consigliate:*',
      'calc_share_text_4': '\n\n💡 Calcolato con Wine Advisor App 🍇',

      // Guida al Servizio & Calici
      'service_card_title': 'Guida al Servizio & Calici',
      'service_card_sub': 'Bicchieri giusti, temperature ideali e trucchi del sommelier.',
      'service_card_badge': 'Sommelier Tips',
      'service_title': 'Servizio & Calici',
      'service_tab_glasses': '🍷 Calici',
      'service_tab_temp': '🌡️ Temp & Decanter',
      'service_tab_hacks': '💡 SOS Sommelier',
      // Calici
      'service_glasses_intro': 'La forma del calice non è una questione estetica: guida il flusso del vino sulle papille gustative e concentra o apre il bouquet aromatico.',
      'glass_tulip_title': 'Calice a Tulipano',
      'glass_tulip_wines': 'Bianchi freschi, giovani e Rosati',
      'glass_tulip_desc': 'Apertura slanciata che trattiene i profumi floreali e agrumati convogliando il vino verso la punta della lingua, dove si esalta l\'acidità vivace.',
      'glass_rhine_title': 'Calice Renano / Grande Luce',
      'glass_rhine_wines': 'Bianchi strutturati, barricati e complessi',
      'glass_rhine_desc': 'Pancia più ampia per permettere al vino di ossigenarsi, liberando aromi secondari di vaniglia, burro e frutta matura.',
      'glass_bordeaux_title': 'Ballon Bordolese',
      'glass_bordeaux_wines': 'Rossi strutturati, tannici e di corpo',
      'glass_bordeaux_desc': 'Altezza elevata e camera d\'aria generosa: permette all\'ossigeno di ammorbidire i tannini spigolosi di vitigni come Cabernet e Sangiovese.',
      'glass_burgundy_title': 'Calice Borgogna (Pancia Larga)',
      'glass_burgundy_wines': 'Rossi eleganti, profumati e sottili',
      'glass_burgundy_desc': 'Forma a palloncino studiata per catturare i profumi sfaccettati di Pinot Nero, Nebbiolo ed Etna Rosso senza sovrastarne la finezza.',
      'glass_flute_title': 'Flûte a Tulipano',
      'glass_flute_wines': 'Spumanti Metodo Classico e Prosecco',
      'glass_flute_desc': 'Fondo a punta per favorire un perlage continuo e risalita fine delle bollicine. Preferire sempre il tulipano alla vecchia coppa aperta.',
      // Temp & Decanter
      'service_temp_intro': 'La temperatura è il fattore che altera di più il gusto del vino: troppo freddo nasconde i profumi, troppo caldo esalta l\'alcol bruciante.',
      'temp_range_sparkling': '6° - 8°C • Spumanti e Prosecchi',
      'temp_sparkling_desc': 'Massima freschezza per esaltare l\'effervescenza e l\'acidità viva.',
      'temp_range_white_light': '8° - 10°C • Bianchi freschi e Rosati',
      'temp_white_light_desc': 'Profumi fruttati puliti e freschezza dissetante.',
      'temp_range_white_rich': '10° - 12°C • Bianchi strutturati e Passiti',
      'temp_white_rich_desc': 'Temperatura più morbida per non contrarre gli aromi complessi del legno.',
      'temp_range_red_light': '14° - 16°C • Rossi giovani e beverini',
      'temp_red_light_desc': 'Fragranza e frutto integro; ottimi serviti con una leggera rinfrescata estiva.',
      'temp_range_red_full': '16° - 18°C • Grandi rossi strutturati',
      'temp_red_full_desc': 'I tannini si sciolgono e il bouquet si esprime al massimo. MAI sopra i 20°C!',
      'decanter_title': 'Guida alla Decantazione',
      'decanter_rule_1_title': 'Rossi giovani e potenti (1-2 ore)',
      'decanter_rule_1_desc': 'Hanno bisogno di un vero "bagno d\'ossigeno" per aprire i tannini chiusi.',
      'decanter_rule_2_title': 'Grandi annate e vecchie riserve (>10 anni)',
      'decanter_rule_2_desc': 'Decantare con estrema delicatezza solo poco prima di servire per separare il deposito. Attenzione: troppa aria potrebbe far svanire profumi fragili!',
      'decanter_rule_3_title': 'Spumanti e rossi freschi: NO decanter',
      'decanter_rule_3_desc': 'Perderebbero all\'istante il perlage o la freschezza fruttata.',
      // SOS Sommelier
      'hack_ice_title': 'Raffreddare in 10 minuti (Ghiaccio + Acqua + Sale)',
      'hack_ice_desc': 'Metti la bottiglia in una glacette con acqua fredda, cubetti di ghiaccio e 2 cucchiai di sale grosso. Il sale abbassa il punto di congelamento e raffredda la bottiglia 4 volte più in fretta del freezer, senza rischiare rotture!',
      'hack_storage_title': 'Conservare la bottiglia aperta',
      'hack_storage_desc': 'Usa una pompetta salvavino sottovuoto o un tappo ermetico e riponi la bottiglia sempre in frigorifero (anche se è un vino rosso!). Il freddo rallenta drasticamente l\'ossidazione.',
      'hack_spoon_title': 'Il cucchiaino nello spumante: Mito sfatato',
      'hack_spoon_desc': 'Mettere il manico di un cucchiaino d\'argento nel collo della bottiglia NON trattiene il gas. Serve esclusivamente un tappo stopper ermetico a gancio.',
      'hack_cork_title': 'Come riconoscere il sentore di tappo (TCA)',
      'hack_cork_desc': 'Se il vino odora di cartone bagnato, cantina ammuffita o panno umido e il frutto è scomparso, si tratta di TCA. Non c\'è rimedio: la bottiglia va sostituita.',

      // Laboratorio di Degustazione & Ruota Aromi
      'lab_card_title': 'Laboratorio di Degustazione',
      'lab_card_sub': 'Ruota degli aromi, esame sensoriale e identikit del vino.',
      'lab_card_badge': 'Degusta & Riconosci',
      'lab_title': 'Laboratorio Sensoriale',
      'lab_step_visual': '1. Vista',
      'lab_step_olfactory': '2. Ruota Aromi',
      'lab_step_taste': '3. Palato',
      'lab_step_result': 'Identikit',
      'lab_visual_title': 'Che colore e tonalità osservi?',
      'lab_visual_sub': 'Inclina il calice su fondo bianco per osservare la tonalità al centro e sull\'unghia.',
      'lab_color_straw_green': 'Giallo Paglierino con riflessi verdolini',
      'lab_color_straw_gold': 'Giallo Dorato brillante',
      'lab_color_rose': 'Rosa Cerasuolo / Petalo',
      'lab_color_ruby': 'Rosso Rubino vivido',
      'lab_color_garnet': 'Rosso Granato con riflessi aranciati',
      'lab_tears_title': 'Consistenza e Lacrime (Archetti)',
      'lab_tears_light': 'Scorrevole e agile (gradazione moderata)',
      'lab_tears_dense': 'Archetti fitti e lenti (ricco di alcol e corpo)',
      'lab_aroma_title': 'Quali profumi riconosci nel calice?',
      'lab_aroma_sub': 'Seleziona da 1 a 5 sentori percepiti portando il naso al calice prima e dopo averlo roteato.',
      'lab_aroma_cat_fruity': '🍓 Fruttato',
      'lab_aroma_cat_floral': '🌸 Floreale',
      'lab_aroma_cat_herbal': '🌿 Vegetale & Erbaceo',
      'lab_aroma_cat_spicy': '🌶️ Speziato & Tostato',
      'lab_aroma_cat_mineral': '🪨 Minerale',
      'aroma_berries': 'Frutti di Bosco',
      'aroma_cherry': 'Ciliegia & Amarena',
      'aroma_apple': 'Mela Verde',
      'aroma_peach': 'Pesca Bianca',
      'aroma_citrus': 'Agrumi & Scorza di Limone',
      'aroma_violet': 'Violetta',
      'aroma_white_flowers': 'Fiori d\'Arancio / Zagara',
      'aroma_rose': 'Rosa Canina',
      'aroma_tomato_leaf': 'Foglia di Pomodoro',
      'aroma_cut_grass': 'Erba Tagliata',
      'aroma_sage': 'Salvia & Erbe Aromatiche',
      'aroma_black_pepper': 'Pepe Nero',
      'aroma_vanilla': 'Vaniglia & Legno Nobile',
      'aroma_cinnamon': 'Cannella',
      'aroma_tobacco': 'Tabacco & Cioccolato',
      'aroma_flint': 'Pietra Focaia',
      'aroma_chalk': 'Gesso & Calcare',
      'lab_taste_title': 'Cosa provi al primo sorso?',
      'lab_taste_sub': 'Fai entrare un filo d\'aria (retro-olfazione) per esaltare acidità, tannini e persistenza.',
      'lab_taste_body': 'Corpo & Struttura:',
      'lab_taste_acidity': 'Freschezza (Acidità):',
      'lab_taste_tannins': 'Tannini (Astringenza):',
      'lab_body_light': 'Leggero & Scattante',
      'lab_body_med': 'Medio ed Equilibrato',
      'lab_body_full': 'Strutturato & Pieno',
      'lab_acid_soft': 'Morbido & Caldo',
      'lab_acid_fresh': 'Fresco & Piacevole',
      'lab_acid_vibrant': 'Vibrante & Tagliente',
      'lab_tan_none': 'Assente / Vellutato (Vini Bianchi)',
      'lab_tan_silky': 'Setoso & Integrato',
      'lab_tan_bold': 'Forte & Deciso (Astringente)',
      'lab_btn_next': 'Prosegui alla Ruota Aromi',
      'lab_btn_to_taste': 'Prosegui al Palato',
      'lab_btn_compute': 'Analizza & Scopri l\'Identikit',
      'lab_btn_restart': 'Nuova Degustazione',
      'lab_match_title': 'Identikit Enologico Rilevato',
      'lab_affinity': 'Affinità col tuo calice:',
      'lab_why_match': 'Perché questo verdetto:',
      'lab_examples_title': 'Vitigni & Denominazioni di riferimento:',
      'lab_share_btn': 'Condividi Scheda Degustazione',
      'lab_share_copied': 'Scheda degustazione copiata! Incollala dove vuoi. 📋',

      // Luxury Home Redesign
      'private_experience': 'Esperienza Privata',
      'good_evening': 'Buonasera',
      'good_morning': 'Buongiorno',
      'good_afternoon': 'Buon pomeriggio',
      'home_search_hint': 'Cerca per etichetta, cantina, vitigno o regione...',
      'what_to_uncork': 'Cosa ti piacerebbe stappare oggi?',
      'filter_all': 'Tutti',
      'filter_reds': 'Rossi strutturati',
      'filter_bubbles': 'Bollicine DOCG',
      'filter_whites': 'Bianchi minerali',
      'filter_bio': 'Biologici',
      'sommelier_month_selection': 'Selezione del Sommelier',
      'current_month': 'Mese Corrente',
      'indicative_price': 'Prezzo indicativo:',
      'olfactory_notes_structure': 'Note Olfattive & Struttura',
      'discover_pairings_btn': 'Abbinamenti Ideali',
      'pairing_of_the_day': 'Abbinamento del Giorno',
      'chef_advice_badge': 'Consiglio Chef',
      'tannic_balance': 'Equilibrio Tannico Perfetto',
      'community_favorites': 'I Più Amati dalla Community',
      'see_all': 'Vedi tutti',
      'scan_banner_title': 'Hai una bottiglia sottomano?',
      'scan_banner_sub': 'Scansiona subito l\'etichetta per voti e note',
      'scan_btn': 'Scansiona',
      'scan_dialog_title': 'Scannerizza Etichetta',
      'scan_dialog_desc': 'Inquadra l\'etichetta della bottiglia con la fotocamera per analizzare vitigno, cantina e recensioni.',
      'scan_camera_btn': 'Apri Fotocamera',
      'scan_gallery_btn': 'Carica da Galleria',
      'nav_home': 'Home',
      'nav_wines': 'Abbinamenti',
      'nav_pairings': 'Abbinamenti',
      'nav_scan': 'Scansione',
      'nav_cellar': 'Cantina',
      'nav_sommelier': 'Sommelier',
      'hub_title': 'I Nostri Percorsi Esclusivi',
      'hub_sub': 'Scegli la modalità ideale per farti guidare.',

      // Scanner Screen & Recognition
      'scanner_nav_title': 'Scansione',
      'scanner_active_badge': 'SCANNER ATTIVO',
      'scanner_flash_on': 'Attiva flash',
      'scanner_flash_off': 'Disattiva flash',
      'scanner_cellar_mode': 'Cantina',
      'scanner_frame_prompt': 'Inquadra l\'etichetta frontale',
      'scanner_manual_entry': 'Inserisci nome manualmente',
      'scanner_manual_title': 'Cerca o Scegli un Vino',
      'scanner_manual_hint': 'Digita il nome del vino...',
      'scanner_match_confirmed': 'Match 99.4% Confermato',
      'scanner_precision_sub': 'Precisione enologica 99.4% · Sigillo Cru',
      'scanner_mode_front': 'Etichetta Fronte',
      'scanner_mode_back': 'Retro / Annata',
      'scanner_mode_list': 'Carta Vini',
      'scanner_prompt_back': 'Inquadra il retro o l\'annata',
      'scanner_prompt_list': 'Inquadra la riga della carta vini',
      'scanner_pro_zoom': 'Zoom Ottico',
      'scanner_score_stamp': 'Punti WA',
      'scanner_rating_label': 'Valutazione',
      'scanner_reviews_count': 'recensioni',
      'scanner_avg_value': 'Valore Medio',
      'scanner_market_range': 'Mercato',
      'scanner_maturation_label': 'Maturazione',
      'scanner_maturation_optimal': 'Ottimale',
      'scanner_maturation_until': 'Fino al',
      'scanner_quote_tignanello': '“Vellutato ed armonico. Trama tannica cesellata con profumi suadenti di mora selvatica, spezie nobili e tabacco tostato.”',
      'scanner_open_sheet': 'Apri Scheda Completa',
      'scanner_add_cellar': 'Aggiungi in Cantina',
      'scanner_added_cellar': 'Aggiunto!',
      'scanner_share_btn': 'Condividi',
      'scanner_share_copied': 'Scheda del vino copiata negli appunti! 📋',
      'scanner_share_text_1': '🍷 *Wine Advisor - Scheda Scansione Bottiglia*\n\n',
      'scanner_share_text_2': '\nValutazione: 4.9 ★ (97 Punti WA)\nPrezzo medio: €135\n\nConsiglio Sommelier: ',

      // Dettaglio Vino Luxury
      'detail_title': 'Dettaglio Vino',
      'cru_historic': 'Cru Storico',
      'est_avg_price': 'prezzo medio stimato',
      'sensory_analysis': 'Analisi Sensoriale',
      'organoleptic_spectrum': 'Spettro Organolettico',
      'vintage_excellent': 'Annata Eccellente',
      'body_label': 'Corpo',
      'body_desc_barolo': 'Intenso e strutturato (85%)',
      'tannin_label': 'Tannino',
      'tannin_desc_barolo': 'Setoso ma persistente (90%)',
      'acidity_label': 'Acidità',
      'acidity_desc_barolo': 'Fresca e vibrante (75%)',
      'sweetness_label': 'Dolcezza',
      'sweetness_desc_barolo': 'Asciutto / Secco (10%)',
      'bouquet_title': 'Bouquet Olfattivo',
      'primary_tertiary_aromas': 'Aromi Primari & Terziari',
      'aroma_rose_dried': 'Rosa Appassita',
      'aroma_rose_dried_sub': 'Sentore floreale nobile',
      'aroma_truffle_tar': 'Goudron & Tartufo',
      'aroma_truffle_tar_sub': 'Complessità terrosa',
      'aroma_cherry_liqueur': 'Ciliegia Sotto Spirito',
      'aroma_cherry_liqueur_sub': 'Frutto maturo e confettura',
      'aroma_dark_spices': 'Spezie Scure',
      'aroma_dark_spices_sub': 'Liquirizia e tabacco',
      'service_temp_label': 'Temperatura',
      'service_temp_desc': '16° - 18°C · Calice Borgogna',
      'decant_time_label': 'Decantazione',
      'decant_time_desc': '2 ore prima',
      'table_art': 'Arte della Tavola',
      'choice_pairings': 'Abbinamenti d\'Elezione',
      'pairing_perfect_badge': 'Perfetto',
      'pairing_territory_badge': 'Territorio',
      'pairing_cheese_badge': 'Formaggi',
      'pairing_dish_1_title': 'Brasato al Barolo',
      'pairing_dish_1_desc': 'Cottura lenta con contorno di morbida polenta concia.',
      'pairing_dish_2_title': 'Risotto al Tartufo',
      'pairing_dish_2_desc': 'Mantecatura impeccabile con lamelle di tartufo bianco d\'Alba.',
      'pairing_dish_3_title': 'Castelmagno DOP',
      'pairing_dish_3_desc': 'Lunga stagionatura per sostenere l\'ampiezza tannica del vino.',
      'winery_terroir_title': 'Origine & Tradizione',
      'winery_name_ceretto': 'La Cantina Ceretto',
      'winery_soil_ceretto': 'Marna di Sant\'Agata Fossili & Arenarie',
      'winery_story_ceretto': 'Nel cuore di Castiglione Falletto sorge il prestigioso Bricco Rocche: un ettaro e mezzo di vigneto gioiello circondato da pareti di cristallo architettoniche. Il terreno argilloso-marnoso, arricchito da venature sabbiose, dona a questo Barolo una setosità inconfondibile unita a una straordinaria capacità di invecchiamento che supera agevolmente i tre decenni.',
      'expand_btn': 'Espandi',
      'collapse_btn': 'Riduci',
      'organic_certified': 'Coltivazione Biologica Certificata',
      'founded_in': 'Fondata nel 1937',
      'in_cellar_btn': 'In Cantina',
      'cellared_btn': 'Custodito',
      'buy_at_price': 'Acquista',
      'added_to_wishlist': 'Aggiunto ai vini desiderati ❤️',
      'removed_from_wishlist': 'Rimosso dai desiderati',
      'cellared_toast': 'Bottiglia aggiunta alla cantina personale! 🍾',
      'removed_cellar_toast': 'Rimosso dall\'inventario della cantina',
      'market_modal_title': 'Acquista presso Enoteche Partner',
      'market_modal_desc': 'Disponibilità verificata presso 4 enoteche selezionate:',

      // Cantina Personale (Cellar Screen)
      'cellar_header_subtitle': 'Cantina',
      'cellar_private_collection': 'Collezione Privata',
      'cellar_active_vault': 'Caveau Attivo',
      'cellar_title': 'La Mia Cantina Personale',
      'cellar_subtitle': 'Archivio termoregolato con monitoraggio del picco evolutivo.',
      'cellar_bottles_stat': 'Bottiglie',
      'cellar_denominations_sub': '8 Denominazioni',
      'cellar_total_value_stat': 'Stima Totale',
      'cellar_value_trend_sub': '+12.4% a/a',
      'cellar_to_drink_stat': 'Da Bere',
      'cellar_active_window_sub': 'Finestra Attiva',
      'cellar_sommelier_nudge_title': 'Consiglio del Sommelier',
      'cellar_sommelier_nudge_body': 'Il Franciacorta Satèn è al culmine. Ideale per stasera!',
      'cellar_nudge_open_btn': 'Apri',
      'cellar_filter_selection': 'Filtra Selezione',
      'cellar_shown_counter': 'mostrate',
      'cellar_filter_all': 'Tutte',
      'cellar_filter_ready': 'Pronte da bere',
      'cellar_filter_aging': 'Invecchiamento',
      'cellar_filter_fav': 'Preferiti',
      'cellar_search_hint': 'Cerca cru, cantina o annata...',
      'cellar_sort_vintage': 'Annata',
      'cellar_sort_score': 'Punteggio',
      'cellar_sort_value': 'Valore',
      'cellar_new_entry_title': 'Nuovo Ingresso',
      'cellar_new_entry_subtitle': 'Scansiona etichetta o inserisci a mano',
      'cellar_add_btn': 'Aggiungi',
      'cellar_custody_title': 'Le Bottiglie in Custodia',
      'cellar_guide_samples': 'ESEMPLARI GUIDA',
      'cellar_status_aging': 'In Affinamento',
      'cellar_status_rest': 'Riposo Ottimale',
      'cellar_status_ready': 'Pronta da bere',
      'cellar_status_drink_start': 'Inizio Beva',
      'cellar_ideal_tonight': 'Ideale stasera!',
      'cellar_window_label': 'Finestra:',
      'cellar_peak_in_years': 'Picco tra 4 anni',
      'cellar_wait_years': 'Attendere ancora 2 anni',
      'cellar_peak_reached': 'Apice qualitativo raggiunto',
      'cellar_harmonious_ready': 'Armonico e pronto',
      'cellar_harvest_label': '(Raccolta)',
      'cellar_analytics_subtitle': 'Analitica del Caveau',
      'cellar_drinker_stats_title': 'Statistiche del Bevitore',
      'cellar_geo_split_subtitle': 'Ripartizione Geografica delle 24 Bottiglie:',
      'cellar_conditions_note': 'Condizioni cantina registrate:',
      'cellar_conditions_val': '14.2°C • 68% Ur',
      'cellar_added_manual_dialog': 'Aggiungi Bottiglia Manualmente',
      'cellar_add_success': 'Nuova bottiglia aggiunta alla cantina! 🍾',

      // Categorie di Vino (ID e Nomi)
      'cat_name_1': 'Bianco Fresco e Leggero',
      'cat_name_2': 'Bollicina Strutturata',
      'cat_name_3': 'Rosso Strutturato',
      'cat_name_4': 'Bianco Strutturato o Bollicina',
      'cat_name_5': 'Rosso Leggero',
      'Bianco Fresco e Leggero': 'Bianco Fresco e Leggero',
      'Bollicina Strutturata': 'Bollicina Strutturata',
      'Rosso Strutturato': 'Rosso Strutturato',
      'Bianco Strutturato o Bollicina': 'Bianco Strutturato o Bollicina',
      'Rosso Leggero': 'Rosso Leggero',

      // Spiegazioni Categorie
      'cat_expl_1': 'Mettiti comodo. Per rilassarti non serve un vino che impegni il palato. Vai su un bianco fresco, fruttato e super beverino. Un calice tira l\'altro!',
      'cat_expl_2': 'Per fare colpo serve classe. Una bollicina Metodo Classico porta un\'atmosfera elegante, sta bene con tutto e il rumore del tappo fa già metà del lavoro.',
      'cat_expl_3': 'Per la carne serve muscolo ed eleganza. I tannini decisi di questo vino si legheranno alla perfezione con la succulenza del piatto, ripulendoti il palato a ogni sorso.',
      'cat_expl_4': 'Con il pesce crudo o saporito serve un vino con buona acidità e profumi netti che non sovrastino la delicatezza del piatto.',
      'cat_expl_5': 'Serve un vino sbarazzino! L\'acidità di piatti come pizza o pasta al pomodoro chiama un rosso fresco, profumato e con pochi tannini.',

      // Cibi (Database & Ricerca)
      'Pizza Margherita': 'Pizza Margherita',
      'Carne alla Griglia': 'Carne alla Griglia',
      'Sushi & Sashimi': 'Sushi & Sashimi',
      'Pasta al Pomodoro': 'Pasta al Pomodoro',
      'Tagliere di Formaggi': 'Tagliere di Formaggi',
      'Hamburger': 'Hamburger',
      'pizza': 'Pizza',
      'meat': 'Carne',
      'fish': 'Pesce',
      'pasta': 'Pasta',
      'cheese': 'Formaggi',

      // Atmosfere / Moods (Database & Ricerca)
      'Netflix & Divano': 'Netflix & Divano',
      'Cena Romantica': 'Cena Romantica',
      'Festa tra amici': 'Festa tra amici',
      'Relax post-lavoro': 'Relax post-lavoro',
      'Pranzo in famiglia': 'Pranzo in famiglia',
      'Voglio fare colpo': 'Voglio fare colpo',

      // Chip Filtro Cibo
      'food_chip_all': 'Tutti',
      'food_chip_pizza': 'Pizza',
      'food_chip_meat': 'Carne',
      'food_chip_fish': 'Pesce',
      'food_chip_pasta': 'Pasta',
      'food_chip_cheese': 'Formaggi',
      'food_chip_burger': 'Hamburger',

      // Mood Filter Chips
      'mood_chip_all': 'Tutti',
      'mood_chip_romantic': 'Romantica',
      'mood_chip_relax': 'Relax',
      'mood_chip_party': 'Festa',
      'mood_chip_couch': 'Divano',
      'mood_chip_family': 'Famiglia',

      // Perfezionamento Cantina & Azioni Rapide
      'cellar_export_btn': 'Esporta Cantina',
      'cellar_export_copied': 'Riepilogo cantina copiato negli appunti! 📋',
      'cellar_cork_btn': 'Stappa 🍾',
      'cellar_corked_toast': 'Salute! Bottiglia stappata con successo 🍾',
      'cellar_empty_filter_title': 'Nessuna bottiglia trovata',
      'cellar_empty_filter_desc': 'Nessun vino corrisponde ai filtri o alla ricerca attiva.',
      'cellar_reset_filters': 'Mostra tutte le bottiglie',
      'cellar_qty_increased': 'Quantità aumentata (+1)',
      'cellar_qty_decreased': 'Quantità ridotta (-1)',
      'cellar_fav_added': 'Aggiunto ai preferiti ❤️',
      'cellar_fav_removed': 'Rimosso dai preferiti',

      // Perfezionamento Sommelier Chat
      'followup_temp': '🌡️ Temp. di servizio ideale?',
      'followup_glass': '🥂 Quale calice consigli?',
      'followup_budget': '💡 Alternative più economiche?',
      'followup_aging': '⏳ Quanti anni può invecchiare?',
      'copied_to_clipboard': 'Risposta copiata negli appunti! 📋',
      'clear_chat_title': 'Cancellare la conversazione?',
      'clear_chat_desc': 'Tutti i messaggi precedenti verranno rimossi.',
      'clear_chat_confirm': 'Cancella tutto',

      // AIS Sensory Profile & Sommelier Details
      'sensory_profile_title': 'Profilo Sensoriale AIS',
      'sensory_profile_sub': 'Analisi tecnica degustativa a 5 dimensioni',
      'sensory_acidity': 'Acidità / Freschezza',
      'sensory_body': 'Corpo / Struttura',
      'sensory_tannin': 'Trama Tannica',
      'sensory_intensity': 'Intensità Aromatica',
      'sensory_softness': 'Morbidezza & Alcol',
      'glassware_title': 'Calice Consigliato',
      'decanting_title': 'Decantazione & Ossigenazione',
      'drinking_window_title': 'Finestra di Beva Ottimale',
      'optimal_year': 'Apice qualitativo previsto',
      'pairings_chef_title': 'Abbinamenti Gastronomici dello Chef',

      // Scanner Perfection
      'scanner_scan_ready_title': 'Mirino Pronto',
      'scanner_scan_ready_sub': 'Inquadra l\'etichetta o tocca un\'opzione per analizzarla',
      'scanner_take_photo': 'Scatta Foto',
      'scanner_upload_photo': 'Carica Foto',
      'scanner_sample_labels': 'Etichette Demo',
      'scanner_close_result': 'Chiudi Risultato',
      'scanner_view_detail_btn': 'Scheda Tecnica Completa 📖',
      'scanner_add_to_cellar_btn': 'Aggiungi in Cantina 🍷',
      'scanner_already_in_cellar': 'Già salvato in cantina ✓',

      // Speech & Audio Sommelier
      'listen_advice': 'Ascolta Sommelier 🔊',
      'stop_advice': 'Ferma Voce ⏹️',
      'speech_playing': 'Riproduzione sommelier in corso...',
    },
    'en': {
      'hello': 'Hello',
      'hero_title': 'What guides\nyour evening?',
      'hero_sub': 'Choose your path to find the perfect wine.',
      'food_title': 'I have the menu',
      'food_sub': 'Find the perfect pairing for your dish.',
      'mood_title': 'I want the right mood',
      'mood_sub': 'A wine for every emotion and situation.',
      'search_title': 'What are you eating tonight?',
      'search_hint': 'E.g. Carbonara, Sushi, Steak...',
      'search_empty': 'Start typing or tap a suggestion...',
      'pairing': 'Pairing:',
      'mood_appbar': 'How are you feeling?',
      'mood_hint': 'E.g. Relaxed, Romantic, Festive...',
      'mood_empty': 'Describe your mood or tap a suggestion...',
      'profile_title': 'My Cellar',
      'profile_empty_title': 'No pairings saved.',
      'profile_empty_sub': 'Explore the app and save your favorites!',
      'profile_deleted': 'Pairing removed from cellar 🗑️',
      'result_title': 'Your Pairing',
      'result_recommended': 'We recommend:',
      'result_examples': 'Examples:',
      'result_why': 'Why this choice?',
      'result_temp': 'Ideal temperature:',
      'result_save': 'Save',
      'result_saved': 'Pairing saved to favorites! 🍷',
      'result_saved_btn': 'Saved to favorites',
      'result_removed': 'Pairing removed from favorites',
      'must_login_to_save': 'Sign in to save favorites to your cellar.',
      'result_dup': 'You already saved this pairing!',
      'share_text_1': '🍷 Great wine tonight!\n\nMy app recommends: *',
      'share_text_2': '*\nExamples: ',
      'share_text_3': '\n\nIdeal temperature: ',
      'share_copied': 'Text copied! Paste it on WhatsApp. 📋',
      'share_tooltip': 'Share',
      'login_title': 'Wine Advisor',
      'login_btn': 'Sign In',
      'register_btn': 'Sign Up',
      'login_prompt': 'Don\'t have an account? Sign Up',
      'register_prompt': 'Already have an account? Sign In',
      'continue_as_guest': 'Continue as guest',
      'guest': 'Guest',
      'guest_title': 'Honored Guest',
      'wine_lover': 'Wine Lover',
      'guest_profile_msg': 'Sign in or register to save your favorite pairings and view them anytime.',
      'guest_login_btn': 'Sign In / Register',
      'email': 'Email',
      'password': 'Password',
      'reg_success': 'Registration completed! You can now sign in.',
      'quick_suggestions': 'Quick suggestions:',
      'all': 'All',
      'food_empty_title': 'No dishes found',
      'food_show_all': 'Show all dishes',
      'mood_empty_title': 'No moods found',
      'mood_show_all': 'Show all moods',
      'refresh': 'Refresh',
      'or': 'or',
      'change_lang': 'Change Language',
      'profile': 'Profile',
      'logout': 'Sign Out',
      'error_prefix': 'Error',
      'network_error': 'Unable to connect to the database. Please check that your Supabase project is active.',
      'my_tasting': 'Your Tasting',
      'tasting_notes': 'Tasting Notes',
      'rate_wine': 'Rate this wine',
      'rating_label': 'Rating',
      'not_rated': 'Not rated yet',
      'stars_count': 'stars out of 5',
      'notes_hint': 'Write your impressions, vintage, dish paired with, occasion...',
      'add_notes': 'Add note',
      'edit_notes': 'Edit note',
      'save_notes': 'Save note',
      'notes_saved': 'Note saved successfully! 📝',
      'delete_notes': 'Delete note',
      'cancel': 'Cancel',
      'no_notes_cantina': 'No notes added yet. Tap to write a note or rate.',

      // Sommelier Quiz
      'quiz_card_title': 'Sommelier Quiz',
      'quiz_card_sub': '3 quick questions to find your ideal glass.',
      'quiz_card_badge': '✨ Recommended',
      'quiz_step_of': 'Step {current} of {total}',
      'quiz_step_1_title': 'What is the mood tonight?',
      'quiz_step_1_sub': 'Choose the atmosphere or occasion',
      'quiz_step_2_title': 'What does your palate crave?',
      'quiz_step_2_sub': 'The taste profile you prefer tonight',
      'quiz_step_3_title': 'Who will you share this glass with?',
      'quiz_step_3_sub': 'The right company makes all the difference',
      'quiz_q1_opt1': 'Casual aperitivo or relaxation',
      'quiz_q1_opt2': 'Romantic dinner or to impress',
      'quiz_q1_opt3': 'BBQ or a rich, flavorful feast',
      'quiz_q1_opt4': 'Pizza, pasta or movie night',
      'quiz_q2_opt1': 'Freshness, floral aromas & vivacity',
      'quiz_q2_opt2': 'Fine bubbles, lively elegance',
      'quiz_q2_opt3': 'Warm body, bold tannins & structure',
      'quiz_q2_opt4': 'Fruity, light, smooth & easy-drinking',
      'quiz_q3_opt1': 'With my partner (an intimate moment)',
      'quiz_q3_opt2': 'A hungry, cheerful group of friends',
      'quiz_q3_opt3': 'Family or guests around the table',
      'quiz_q3_opt4': 'Solo, for some well-deserved relaxation',
      'quiz_analyzing': 'The Sommelier is finding your perfect match...',
      'quiz_match_title': 'Here is your ideal match!',
      'quiz_affinity': 'Sommelier Affinity',
      'quiz_why_match': 'Why it\'s perfect for you:',
      'quiz_see_details': 'View bottles & details',
      'quiz_retake': 'Retake Quiz',

      // Reverse Pairing
      'reverse_card_title': 'I have the bottle',
      'reverse_card_sub': 'What to cook? Find the best dishes for your wine.',
      'reverse_title': 'Reverse Pairing',
      'reverse_subtitle': 'Choose or search the wine you have at home to see what to cook:',
      'reverse_search_hint': 'Search by name (e.g. Barolo, Chianti, Prosecco...)',
      'reverse_dishes_title': 'Recommended dishes & recipes',
      'reverse_chef_tip': 'Chef\'s Tip:',
      'reverse_why': 'Why it works:',
      'reverse_filter_all': 'All',
      'reverse_filter_primi': '🍝 Pasta & Rice',
      'reverse_filter_meat': '🥩 Meat',
      'reverse_filter_fish': '🐟 Seafood',
      'reverse_filter_pizza': '🍕 Pizza & Casual',
      'reverse_filter_cheese': '🧀 Cheese',
      'reverse_no_dishes': 'No dishes found for this filter.',

      // Wine Bottle Calculator
      'calc_card_title': 'Wine Bottle Calculator',
      'calc_card_sub': 'How many bottles do you need for your dinner or party?',
      'calc_card_badge': 'Party & Dinners',
      'calc_title': 'Wine Calculator',
      'calc_subtitle': 'Plan wine quantities for dinners and parties without running dry or wasting wine.',
      'calc_guests_title': 'Number of Guests',
      'calc_guests_unit': 'guests',
      'calc_occasion_title': 'Occasion Type',
      'calc_occ_aperitivo': '🥂 Cocktail / Aperitivo',
      'calc_occ_casual': '🍕 Pizza & Casual',
      'calc_occ_dinner': '🍷 Full Dinner',
      'calc_occ_party': '🎉 Party with Friends',
      'calc_style_title': 'Drinking Pace',
      'calc_style_light': 'Light (moderate)',
      'calc_style_med': 'Standard (wine lovers)',
      'calc_style_heavy': 'Festive (long night)',
      'calc_result_title': 'Recommended Bottles',
      'calc_total_bottles': 'Total Bottles',
      'calc_reserve_badge': 'incl. 1 reserve',
      'calc_glasses_est': 'Estimated total glasses:',
      'calc_sparkling': 'Sparkling / Prosecco',
      'calc_white': 'White / Rosé Wines',
      'calc_red': 'Red Wines',
      'calc_reserve': 'Safety Reserve Bottle',
      'calc_reserve_tip': 'Sommelier Tip: Always keep 1 reserve bottle chilled or in your cellar. If guests stay longer and celebrate, it will save the night!',
      'calc_share_btn': 'Share Wine Shopping List',
      'calc_share_copied': 'Wine shopping list copied to clipboard! 📋',
      'calc_share_text_1': '🍷 *Wine Shopping List for Event*\nGuests: ',
      'calc_share_text_2': ' people\nOccasion: ',
      'calc_share_text_3': '\n\n🍾 *Recommended bottles:*',
      'calc_share_text_4': '\n\n💡 Calculated with Wine Advisor App 🍇',

      // Service & Glassware Guide
      'service_card_title': 'Service & Glassware Guide',
      'service_card_sub': 'Proper glasses, ideal temperatures, and sommelier hacks.',
      'service_card_badge': 'Sommelier Tips',
      'service_title': 'Service & Glassware',
      'service_tab_glasses': '🍷 Glassware',
      'service_tab_temp': '🌡️ Temp & Decanting',
      'service_tab_hacks': '💡 Sommelier SOS',
      // Glassware
      'service_glasses_intro': 'Glass shape is not about aesthetics: it directs the wine flow across your taste buds and focuses or opens delicate aromas.',
      'glass_tulip_title': 'Tulip Glass',
      'glass_tulip_wines': 'Crisp Whites, Young Whites & Rosés',
      'glass_tulip_desc': 'Tapered rim preserves fresh floral aromas and directs wine to the tip of the tongue where vibrant acidity shines.',
      'glass_rhine_title': 'Rhine / Large Bowl Glass',
      'glass_rhine_wines': 'Full-bodied, oaked & complex Whites',
      'glass_rhine_desc': 'Wider bowl provides aeration, releasing secondary notes of oak, butter, and ripe fruit.',
      'glass_bordeaux_title': 'Bordeaux Balloon Glass',
      'glass_bordeaux_wines': 'Structured, tannic & bold Reds',
      'glass_bordeaux_desc': 'Tall bowl with generous breathing room allows oxygen to soften astringent tannins in Cabernet, Nebbiolo, and Sangiovese.',
      'glass_burgundy_title': 'Burgundy Balloon Glass',
      'glass_burgundy_wines': 'Delicate, fragrant & complex Reds',
      'glass_burgundy_desc': 'Wide spherical bowl captures subtle aromatic nuances of Pinot Noir and Etna Rosso without overwhelming delicacy.',
      'glass_flute_title': 'Tulip Champagne Flute',
      'glass_flute_wines': 'Classic Method Sparkling & Prosecco',
      'glass_flute_desc': 'Pointed base fosters a persistent bead of bubbles. Always prefer a tulip flute over wide coupes for dry sparkling.',
      // Temp & Decanter
      'service_temp_intro': 'Temperature is the single biggest factor altering wine flavor: too cold hides delicate aromas, too warm accentuates harsh alcohol heat.',
      'temp_range_sparkling': '6° - 8°C • Sparkling & Prosecco',
      'temp_sparkling_desc': 'Maximum chill to highlight lively effervescence and crisp acidity.',
      'temp_range_white_light': '8° - 10°C • Crisp Whites & Rosés',
      'temp_white_light_desc': 'Clean fruit aromatics and thirst-quenching freshness.',
      'temp_range_white_rich': '10° - 12°C • Rich Whites & Sweet Wines',
      'temp_white_rich_desc': 'Gentler chill to prevent suppressing oak and aged complexity.',
      'temp_range_red_light': '14° - 16°C • Light & fresh Reds',
      'temp_red_light_desc': 'Bright fruit aromas; delightfully refreshing with a light summer chill.',
      'temp_range_red_full': '16° - 18°C • Bold & structured Reds',
      'temp_red_full_desc': 'Tannins soften and full bouquet flourishes. NEVER serve above 20°C!',
      'decanter_title': 'Decanting & Aeration Guide',
      'decanter_rule_1_title': 'Young & powerful reds (1-2 hours)',
      'decanter_rule_1_desc': 'Need an oxygen bath to open up tightly wound tannins and reveal complex fruit.',
      'decanter_rule_2_title': 'Old vintages & aged reserves (>10 years)',
      'decanter_rule_2_desc': 'Decant very gently right before serving solely to separate sediment. Caution: fragile aged aromas can dissipate quickly!',
      'decanter_rule_3_title': 'Sparkling & light reds: DO NOT decant',
      'decanter_rule_3_desc': 'They will quickly lose carbonation or youthful fruit vibrancy.',
      // SOS Sommelier
      'hack_ice_title': 'Chill in 10 Minutes (Ice + Water + Salt)',
      'hack_ice_desc': 'Submerge the bottle in an ice bucket with water, ice cubes, and 2 tbsp coarse salt. Salt lowers the freezing point, chilling 4x faster than a freezer without risk of bottle explosion!',
      'hack_storage_title': 'Preserving an Opened Bottle',
      'hack_storage_desc': 'Use a vacuum wine pump or hermetic stopper and always store in the fridge (even red wine!). Cold temperatures drastically slow oxidation.',
      'hack_spoon_title': 'Spoon in Sparkling Wine: Myth Debunked',
      'hack_spoon_desc': 'Placing a silver spoon handle in the bottle neck does NOT preserve bubbles. You need an airtight champagne stopper.',
      'hack_cork_title': 'How to Detect Cork Taint (TCA)',
      'hack_cork_desc': 'If wine smells of wet cardboard, damp cellar, or moldy dishrags and fruit is completely dead, it has cork taint. Replace the bottle.',

      // Tasting Lab & Aroma Wheel
      'lab_card_title': 'Wine Tasting Lab',
      'lab_card_sub': 'Aroma wheel, sensory exam, and wine profile match.',
      'lab_card_badge': 'Taste & Discover',
      'lab_title': 'Sensory Tasting Lab',
      'lab_step_visual': '1. Visual',
      'lab_step_olfactory': '2. Aroma Wheel',
      'lab_step_taste': '3. Palate',
      'lab_step_result': 'Profile Match',
      'lab_visual_title': 'What color and hue do you see?',
      'lab_visual_sub': 'Tilt the glass against a white background to inspect center and rim hue.',
      'lab_color_straw_green': 'Straw Yellow with greenish reflections',
      'lab_color_straw_gold': 'Bright Golden Yellow',
      'lab_color_rose': 'Cherry / Petal Rosé',
      'lab_color_ruby': 'Vibrant Ruby Red',
      'lab_color_garnet': 'Garnet Red with orange glints',
      'lab_tears_title': 'Viscosity & Tears (Legs)',
      'lab_tears_light': 'Fluid & swift legs (moderate alcohol)',
      'lab_tears_dense': 'Dense & slow tears (high alcohol and body)',
      'lab_aroma_title': 'What aromas do you detect in the glass?',
      'lab_aroma_sub': 'Pick 1 to 5 scents perceived by bringing your nose to the glass before and after swirling.',
      'lab_aroma_cat_fruity': '🍓 Fruity',
      'lab_aroma_cat_floral': '🌸 Floral',
      'lab_aroma_cat_herbal': '🌿 Herbal & Green',
      'lab_aroma_cat_spicy': '🌶️ Spicy & Oak',
      'lab_aroma_cat_mineral': '🪨 Mineral',
      'aroma_berries': 'Wild Berries',
      'aroma_cherry': 'Cherry & Dark Cherry',
      'aroma_apple': 'Green Apple',
      'aroma_peach': 'White Peach',
      'aroma_citrus': 'Citrus & Lemon Zest',
      'aroma_violet': 'Violet',
      'aroma_white_flowers': 'Orange Blossom / White Flowers',
      'aroma_rose': 'Wild Rose',
      'aroma_tomato_leaf': 'Tomato Leaf',
      'aroma_cut_grass': 'Fresh Cut Grass',
      'aroma_sage': 'Sage & Garden Herbs',
      'aroma_black_pepper': 'Black Pepper',
      'aroma_vanilla': 'Vanilla & Noble Oak',
      'aroma_cinnamon': 'Cinnamon',
      'aroma_tobacco': 'Tobacco & Dark Chocolate',
      'aroma_flint': 'Flint / Gunpowder',
      'aroma_chalk': 'Chalk & Limestone',
      'lab_taste_title': 'What does your first sip reveal?',
      'lab_taste_sub': 'Aerate slightly in your mouth to discern acidity, tannins, and finish length.',
      'lab_taste_body': 'Body & Structure:',
      'lab_taste_acidity': 'Freshness (Acidity):',
      'lab_taste_tannins': 'Tannins (Astringency):',
      'lab_body_light': 'Light & Crisp',
      'lab_body_med': 'Medium & Balanced',
      'lab_body_full': 'Full & Structured',
      'lab_acid_soft': 'Soft & Warm',
      'lab_acid_fresh': 'Fresh & Pleasant',
      'lab_acid_vibrant': 'Vibrant & Tart',
      'lab_tan_none': 'None / Silky (White Wines)',
      'lab_tan_silky': 'Silky & Integrated',
      'lab_tan_bold': 'Bold & Grippy (Astringent)',
      'lab_btn_next': 'Proceed to Aroma Wheel',
      'lab_btn_to_taste': 'Proceed to Palate Exam',
      'lab_btn_compute': 'Analyze & Reveal Wine Profile',
      'lab_btn_restart': 'Start New Tasting',
      'lab_match_title': 'Identified Wine Profile',
      'lab_affinity': 'Sensory match score:',
      'lab_why_match': 'Why this matches:',
      'lab_examples_title': 'Benchmark Grape Varieties & Appellations:',
      'lab_share_btn': 'Share Tasting Sheet',
      'lab_share_copied': 'Tasting sheet copied! Paste it anywhere. 📋',

      // Luxury Home Redesign
      'private_experience': 'Private Experience',
      'good_evening': 'Good evening',
      'good_morning': 'Good morning',
      'good_afternoon': 'Good afternoon',
      'home_search_hint': 'Search by label, winery, grape, or region...',
      'what_to_uncork': 'What would you like to uncork today?',
      'filter_all': 'All',
      'filter_reds': 'Structured Reds',
      'filter_bubbles': 'DOCG Sparkling',
      'filter_whites': 'Mineral Whites',
      'filter_bio': 'Organic',
      'sommelier_month_selection': 'Sommelier\'s Selection',
      'current_month': 'Current Month',
      'indicative_price': 'Approximate price:',
      'olfactory_notes_structure': 'Aromatic Notes & Body',
      'discover_pairings_btn': 'Ideal Pairings',
      'pairing_of_the_day': 'Pairing of the Day',
      'chef_advice_badge': 'Chef\'s Advice',
      'tannic_balance': 'Perfect Tannic Balance',
      'community_favorites': 'Community Favorites',
      'see_all': 'See all',
      'scan_banner_title': 'Have a bottle at hand?',
      'scan_banner_sub': 'Scan the label now for ratings & notes',
      'scan_btn': 'Scan',
      'scan_dialog_title': 'Scan Wine Label',
      'scan_dialog_desc': 'Frame the bottle label with your camera to detect grape variety, winery, and community tasting notes.',
      'scan_camera_btn': 'Open Camera',
      'scan_gallery_btn': 'Upload from Gallery',
      'nav_home': 'Home',
      'nav_wines': 'Pairings',
      'nav_pairings': 'Pairings',
      'nav_scan': 'Scan',
      'nav_cellar': 'Cellar',
      'nav_sommelier': 'Sommelier',
      'hub_title': 'Our Exclusive Paths',
      'hub_sub': 'Select how you would like to be guided.',

      // Scanner Screen & Recognition
      'scanner_nav_title': 'Scanner',
      'scanner_active_badge': 'SCANNER ACTIVE',
      'scanner_flash_on': 'Turn on flash',
      'scanner_flash_off': 'Turn off flash',
      'scanner_cellar_mode': 'Cellar',
      'scanner_frame_prompt': 'Frame front label',
      'scanner_manual_entry': 'Enter wine name manually',
      'scanner_manual_title': 'Search or Select a Wine',
      'scanner_manual_hint': 'Type wine name...',
      'scanner_match_confirmed': '99.4% Match Confirmed',
      'scanner_precision_sub': 'Enological precision 99.4% · Cru Seal',
      'scanner_mode_front': 'Front Label',
      'scanner_mode_back': 'Back / Vintage',
      'scanner_mode_list': 'Wine List',
      'scanner_prompt_back': 'Frame back label or vintage',
      'scanner_prompt_list': 'Frame wine list row or menu',
      'scanner_pro_zoom': 'Optical Zoom',
      'scanner_score_stamp': 'WA Points',
      'scanner_rating_label': 'Rating',
      'scanner_reviews_count': 'reviews',
      'scanner_avg_value': 'Avg Value',
      'scanner_market_range': 'Market',
      'scanner_maturation_label': 'Maturation',
      'scanner_maturation_optimal': 'Optimal',
      'scanner_maturation_until': 'Until',
      'scanner_quote_tignanello': '“Velvety and harmonious. Chiseled tannic texture with alluring scents of wild blackberry, noble spices, and toasted tobacco.”',
      'scanner_open_sheet': 'Open Full Wine Sheet',
      'scanner_add_cellar': 'Add to Cellar',
      'scanner_added_cellar': 'Added!',
      'scanner_share_btn': 'Share',
      'scanner_share_copied': 'Wine sheet copied to clipboard! 📋',
      'scanner_share_text_1': '🍷 *Wine Advisor - Scanned Wine Card*\n\n',
      'scanner_share_text_2': '\nRating: 4.9 ★ (97 WA Points)\nAvg price: €135\n\nSommelier Note: ',

      // Luxury Wine Detail
      'detail_title': 'Wine Details',
      'cru_historic': 'Historic Cru',
      'est_avg_price': 'estimated average price',
      'sensory_analysis': 'Sensory Analysis',
      'organoleptic_spectrum': 'Organoleptic Spectrum',
      'vintage_excellent': 'Outstanding Vintage',
      'body_label': 'Body',
      'body_desc_barolo': 'Intense & structured (85%)',
      'tannin_label': 'Tannin',
      'tannin_desc_barolo': 'Silky yet persistent (90%)',
      'acidity_label': 'Acidity',
      'acidity_desc_barolo': 'Fresh & vibrant (75%)',
      'sweetness_label': 'Sweetness',
      'sweetness_desc_barolo': 'Dry / Bone-dry (10%)',
      'bouquet_title': 'Olfactory Bouquet',
      'primary_tertiary_aromas': 'Primary & Tertiary Aromas',
      'aroma_rose_dried': 'Dried Rose',
      'aroma_rose_dried_sub': 'Noble floral nuance',
      'aroma_truffle_tar': 'Tar & Truffle',
      'aroma_truffle_tar_sub': 'Earthy complexity',
      'aroma_cherry_liqueur': 'Brandied Cherry',
      'aroma_cherry_liqueur_sub': 'Ripe fruit & jammy finish',
      'aroma_dark_spices': 'Dark Spices',
      'aroma_dark_spices_sub': 'Licorice & toasted tobacco',
      'service_temp_label': 'Temperature',
      'service_temp_desc': '16° - 18°C · Burgundy Balloon',
      'decant_time_label': 'Decanting',
      'decant_time_desc': '2 hours prior',
      'table_art': 'Art of Dining',
      'choice_pairings': 'Prime Pairings',
      'pairing_perfect_badge': 'Perfect',
      'pairing_territory_badge': 'Heritage',
      'pairing_cheese_badge': 'Cheeses',
      'pairing_dish_1_title': 'Braised Beef in Barolo',
      'pairing_dish_1_desc': 'Slow-cooked beef paired with creamy, rich polenta.',
      'pairing_dish_2_title': 'White Truffle Risotto',
      'pairing_dish_2_desc': 'Flawless butter mantecatura topped with Alba white truffle shavings.',
      'pairing_dish_3_title': 'Castelmagno DOP',
      'pairing_dish_3_desc': 'Aged Alpine cheese built to stand up to the bold tannic structure.',
      'winery_terroir_title': 'Origin & Heritage',
      'winery_name_ceretto': 'Ceretto Winery',
      'winery_soil_ceretto': 'Sant\'Agata Fossil Marls & Sandstones',
      'winery_story_ceretto': 'In the heart of Castiglione Falletto lies the iconic Bricco Rocche: a pristine 1.5-hectare jewel vineyard crowned by a modern glass cube. The clay-marl soil infused with sandy veins gives this Barolo an unmistakably silky mouthfeel paired with extraordinary aging potential easily exceeding three decades.',
      'expand_btn': 'Expand',
      'collapse_btn': 'Collapse',
      'organic_certified': 'Certified Organic Viticulture',
      'founded_in': 'Founded in 1937',
      'in_cellar_btn': 'In Cellar',
      'cellared_btn': 'Cellared',
      'buy_at_price': 'Purchase',
      'added_to_wishlist': 'Added to wishlist ❤️',
      'removed_from_wishlist': 'Removed from wishlist',
      'cellared_toast': 'Bottle added to your personal cellar! 🍾',
      'removed_cellar_toast': 'Removed from cellar inventory',
      'market_modal_title': 'Purchase from Partner Wine Shops',
      'market_modal_desc': 'Verified stock across 4 curated partner merchants:',

      // Personal Cellar (Cellar Screen)
      'cellar_header_subtitle': 'Cellar',
      'cellar_private_collection': 'Private Collection',
      'cellar_active_vault': 'Active Vault',
      'cellar_title': 'My Personal Cellar',
      'cellar_subtitle': 'Climate-controlled archive with evolutionary peak monitoring.',
      'cellar_bottles_stat': 'Bottles',
      'cellar_denominations_sub': '8 Appellations',
      'cellar_total_value_stat': 'Total Value',
      'cellar_value_trend_sub': '+12.4% YoY',
      'cellar_to_drink_stat': 'To Drink',
      'cellar_active_window_sub': 'Active Window',
      'cellar_sommelier_nudge_title': 'Sommelier Recommendation',
      'cellar_sommelier_nudge_body': 'Franciacorta Satèn is at its peak. Perfect for tonight!',
      'cellar_nudge_open_btn': 'Open',
      'cellar_filter_selection': 'Filter Selection',
      'cellar_shown_counter': 'shown',
      'cellar_filter_all': 'All',
      'cellar_filter_ready': 'Ready to drink',
      'cellar_filter_aging': 'Aging',
      'cellar_filter_fav': 'Favorites',
      'cellar_search_hint': 'Search cru, winery, or vintage...',
      'cellar_sort_vintage': 'Vintage',
      'cellar_sort_score': 'Score',
      'cellar_sort_value': 'Value',
      'cellar_new_entry_title': 'New Entry',
      'cellar_new_entry_subtitle': 'Scan label or enter manually',
      'cellar_add_btn': 'Add',
      'cellar_custody_title': 'Bottles in Custody',
      'cellar_guide_samples': 'CURATED SAMPLES',
      'cellar_status_aging': 'Aging',
      'cellar_status_rest': 'Optimal Rest',
      'cellar_status_ready': 'Ready to drink',
      'cellar_status_drink_start': 'Drinking Window Opened',
      'cellar_ideal_tonight': 'Ideal tonight!',
      'cellar_window_label': 'Window:',
      'cellar_peak_in_years': 'Peak in 4 years',
      'cellar_wait_years': 'Wait 2 more years',
      'cellar_peak_reached': 'Qualitative peak reached',
      'cellar_harmonious_ready': 'Harmonious & ready',
      'cellar_harvest_label': '(Harvest)',
      'cellar_analytics_subtitle': 'Vault Analytics',
      'cellar_drinker_stats_title': 'Drinker Statistics',
      'cellar_geo_split_subtitle': 'Geographic Breakdown of 24 Bottles:',
      'cellar_conditions_note': 'Recorded cellar conditions:',
      'cellar_conditions_val': '14.2°C • 68% RH',
      'cellar_added_manual_dialog': 'Add Bottle Manually',
      'cellar_add_success': 'New bottle added to your cellar! 🍾',

      // Wine Categories (ID & Names)
      'cat_name_1': 'Crisp & Light White',
      'cat_name_2': 'Structured Sparkling',
      'cat_name_3': 'Full-bodied Red',
      'cat_name_4': 'Full-bodied White or Sparkling',
      'cat_name_5': 'Light Red',
      'Bianco Fresco e Leggero': 'Crisp & Light White',
      'Bollicina Strutturata': 'Structured Sparkling',
      'Rosso Strutturato': 'Full-bodied Red',
      'Bianco Strutturato o Bollicina': 'Full-bodied White or Sparkling',
      'Rosso Leggero': 'Light Red',

      // Category Explanations
      'cat_expl_1': 'Make yourself comfortable. To relax, you don\'t need an overwhelming wine. Choose a fresh, fruity, and super easy-drinking white. One glass leads to another!',
      'cat_expl_2': 'To make an impression, you need class. A Classic Method bubbly creates an elegant vibe, pairs with everything, and the pop of the cork already does half the job.',
      'cat_expl_3': 'Meat calls for muscle and elegance. The bold tannins of this wine will pair seamlessly with the savory richness of the dish, cleansing your palate with every sip.',
      'cat_expl_4': 'With raw or flavorful seafood, you need a wine with vibrant acidity and crisp aromas that won\'t overpower the delicacy of the dish.',
      'cat_expl_5': 'You need a playful wine! The acidity of dishes like pizza or tomato pasta calls for a fresh, aromatic red with light tannins.',

      // Foods (Database & Search)
      'Pizza Margherita': 'Margherita Pizza',
      'Carne alla Griglia': 'Grilled Meat',
      'Sushi & Sashimi': 'Sushi & Sashimi',
      'Pasta al Pomodoro': 'Tomato Pasta',
      'Tagliere di Formaggi': 'Cheese Platter',
      'Hamburger': 'Burger',
      'pizza': 'Pizza',
      'meat': 'Meat',
      'fish': 'Fish',
      'pasta': 'Pasta',
      'cheese': 'Cheese',

      // Moods (Database & Search)
      'Netflix & Divano': 'Netflix & Couch',
      'Cena Romantica': 'Romantic Dinner',
      'Festa tra amici': 'Party with Friends',
      'Relax post-lavoro': 'After-Work Relax',
      'Pranzo in famiglia': 'Family Lunch',
      'Voglio fare colpo': 'Want to Impress',

      // Food Filter Chips
      'food_chip_all': 'All',
      'food_chip_pizza': 'Pizza',
      'food_chip_meat': 'Meat',
      'food_chip_fish': 'Fish',
      'food_chip_pasta': 'Pasta',
      'food_chip_cheese': 'Cheese',
      'food_chip_burger': 'Burger',

      // Mood Filter Chips
      'mood_chip_all': 'All',
      'mood_chip_romantic': 'Romantic',
      'mood_chip_relax': 'Relax',
      'mood_chip_party': 'Party',
      'mood_chip_couch': 'Couch',
      'mood_chip_family': 'Family',

      // Cellar Perfection & Quick Actions
      'cellar_export_btn': 'Export Cellar',
      'cellar_export_copied': 'Cellar summary copied to clipboard! 📋',
      'cellar_cork_btn': 'Uncork 🍾',
      'cellar_corked_toast': 'Cheers! Bottle uncorked successfully 🍾',
      'cellar_empty_filter_title': 'No bottles found',
      'cellar_empty_filter_desc': 'No wine matches the current search or active filter.',
      'cellar_reset_filters': 'Show all bottles',
      'cellar_qty_increased': 'Quantity increased (+1)',
      'cellar_qty_decreased': 'Quantity reduced (-1)',
      'cellar_fav_added': 'Added to favorites ❤️',
      'cellar_fav_removed': 'Removed from favorites',

      // Sommelier Chat Perfection
      'followup_temp': '🌡️ Ideal serving temperature?',
      'followup_glass': '🥂 What glassware do you recommend?',
      'followup_budget': '💡 More affordable alternatives?',
      'followup_aging': '⏳ How many years can it age?',
      'copied_to_clipboard': 'Advice copied to clipboard! 📋',
      'clear_chat_title': 'Clear conversation?',
      'clear_chat_desc': 'All previous messages will be removed.',
      'clear_chat_confirm': 'Clear all',

      // AIS Sensory Profile & Sommelier Details
      'sensory_profile_title': 'AIS Sensory Profile',
      'sensory_profile_sub': '5-dimension technical tasting evaluation',
      'sensory_acidity': 'Acidity / Freshness',
      'sensory_body': 'Body / Structure',
      'sensory_tannin': 'Tannic Texture',
      'sensory_intensity': 'Aromatic Intensity',
      'sensory_softness': 'Smoothness & Alcohol',
      'glassware_title': 'Recommended Glassware',
      'decanting_title': 'Decanting & Aeration',
      'drinking_window_title': 'Optimal Drinking Window',
      'optimal_year': 'Predicted peak vintage',
      'pairings_chef_title': 'Chef\'s Gastronomic Pairings',

      // Scanner Perfection
      'scanner_scan_ready_title': 'Viewfinder Ready',
      'scanner_scan_ready_sub': 'Frame label or tap an option to analyze',
      'scanner_take_photo': 'Take Photo',
      'scanner_upload_photo': 'Upload Photo',
      'scanner_sample_labels': 'Demo Labels',
      'scanner_close_result': 'Close Result',
      'scanner_view_detail_btn': 'Full Technical Sheet 📖',
      'scanner_add_to_cellar_btn': 'Add to Cellar 🍷',
      'scanner_already_in_cellar': 'Already in cellar ✓',

      // Speech & Audio Sommelier
      'listen_advice': 'Listen to Sommelier 🔊',
      'stop_advice': 'Stop Voice ⏹️',
      'speech_playing': 'Sommelier voice playing...',
    },
  };
  return dict[appLang.value]?[key] ?? key;
}
// ========================================================

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  try {
    final prefs = await SharedPreferences.getInstance();
    final savedLang = prefs.getString('app_lang');
    if (savedLang != null) {
      appLang.value = savedLang;
    }
    appLang.addListener(() {
      prefs.setString('app_lang', appLang.value);
    });
  } catch (e) {
    debugPrint('Prefs init warning: $e');
  }

  try {
    await Supabase.initialize(
      url: 'https://mqwayxigacinvjxcdlxb.supabase.co',
      publishableKey:
          'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xd2F5eGlnYWNpbnZqeGNkbHhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUyNDEzNDQsImV4cCI6MjEwMDgxNzM0NH0.C96jQnR2ducj__h2smr8zJiZp5avZA5Zbf-BWvvz-tY',
    );
  } catch (e) {
    debugPrint('Supabase init warning: $e');
  }

  runApp(const WineAdvisorApp());
}

class WineAdvisorApp extends StatelessWidget {
  const WineAdvisorApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Wine Advisor',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        scaffoldBackgroundColor: const Color(0xFFFCF9F6),
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF3C0311),
          primary: const Color(0xFF3C0311),
          primaryContainer: const Color(0xFF581825),
          secondary: const Color(0xFF7B581C),
          secondaryContainer: const Color(0xFFFDCC85),
          surface: Colors.white,
        ),
        textTheme: GoogleFonts.plusJakartaSansTextTheme(Theme.of(context).textTheme)
            .copyWith(
              headlineLarge: GoogleFonts.playfairDisplay(
                color: const Color(0xFF3C0311),
                fontWeight: FontWeight.bold,
              ),
              headlineMedium: GoogleFonts.playfairDisplay(
                color: const Color(0xFF3C0311),
                fontWeight: FontWeight.bold,
              ),
              titleLarge: GoogleFonts.playfairDisplay(
                color: const Color(0xFF3C0311),
                fontWeight: FontWeight.bold,
              ),
            ),
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.transparent,
          elevation: 0,
          centerTitle: true,
          iconTheme: IconThemeData(color: Color(0xFF3C0311)),
        ),
        cardTheme: CardThemeData(
          color: Colors.white,
          surfaceTintColor: Colors.transparent,
          elevation: 4,
          shadowColor: const Color(0xFF2C2224).withValues(alpha: 0.08),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(20),
          ),
        ),
        floatingActionButtonTheme: const FloatingActionButtonThemeData(
          backgroundColor: Color(0xFF581825),
          foregroundColor: Colors.white,
          elevation: 6,
          shape: StadiumBorder(),
        ),
      ),
      home: const HomeScreen(),
    );
  }
}

class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  @override
  Widget build(BuildContext context) {
    try {
      final client = Supabase.instance.client;
      return StreamBuilder<AuthState>(
        stream: client.auth.onAuthStateChange,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting &&
              client.auth.currentSession == null) {
            return const Scaffold(
              body: Center(child: CircularProgressIndicator()),
            );
          }
          final session = snapshot.data?.session ?? client.auth.currentSession;
          if (session != null) return const HomeScreen();
          return const LoginScreen();
        },
      );
    } catch (_) {
      return const LoginScreen();
    }
  }
}

final supabase = Supabase.instance.client;
